name: PermissionsEx
main: ru.tehkode.permissions.bukkit.PermissionsEx
version: 1.19.3
author: rymate1234
website: www.bukkit.org
description: PermissionsEx - New powerful users and groups permissions management plugin..... PHAHAHAHAHA. You gotta be joking me! XD XD XD